import "./globals.scss";
import "antd/dist/reset.css";

export const metadata = {
  title: "Digital Showroom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
